method: gpadmm_full

common:
  dataset: imagenet
  model: resnet50
  seed: 1
  batch_size: 128
  device: "cuda:1"
  test_batch_size: 256
  data_dir: ~/imagenet
  output_dir: ./output/gpadmm_imagenet_resnet50_s90_lr002_c4_i8.jsonl
  save_dir: ./runs/gpadmm_imagenet_resnet50_s90_lr002_c4_i8

  # torchvision pretrained 사용 -> 사전학습 단계 생략
  num_pre_epochs: 0

  optimizer: sgd
  lr: 0.02
  retrain_lr: 0.005
  momentum: 0.9
  weight_decay: 0.0001
  nesterov: true
  rho: 0.01

gpadmm:
  gpadmm_prune_scope: global
  sparsity: 0.9
  num_cycles: 4
  grow_interval: 8
  num_re_epochs: 15
  c: 0.8
  min_layer_keep_ratio: 0.01
